name: Publish NPM package

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node packages
        working-directory: gefyra/
        run: npm ci
      - uses: JS-DevTools/npm-publish@v2
        with:
          package: ./gefyra/package.json
          token: ${{ secrets.NPM_TOKEN }}

