name: Lint and test typescript binding

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Node packages
      working-directory: gefyra/
      run: npm ci
    - name: Lint
      working-directory: gefyra/
      run: |
        npm run lint
    - uses: AbsaOSS/k3d-action@v2
      name: Create Single Cluster
      with:
        cluster-name: "mycluster"
        args: >-
          --agents 1
          -p "31820:31820/UDP@agent:0"
          --image docker.io/rancher/k3s:v1.25.6-k3s1
    - name: Test
      working-directory: gefyra/
      run: |
        npm run test
